# Generated by Django 4.1.2 on 2022-10-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['date_created']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='created',
            new_name='date_created',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='company_reference',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='registered_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
